set encoding=utf-8
set fileencoding=utf-8
set nocompatible
set nobackup noswapfile
set autoread
set number
set nowrap
set startofline
set scrolloff=3
set splitbelow splitright

set hlsearch incsearch showmatch
set ignorecase smartcase nowrapscan

set textwidth=100
set colorcolumn=+1,+2,+3
set formatoptions-=t

set cindent ai si et
set ts=2 sts=2 sw=2 bs=2

set hidden

set updatetime=300
set shortmess+=c

if &shell !~# '\(/\(zsh\|bash\|sh\)\|\\\\cmd\.exe\)$'
  set shell=/bin/bash
endif

set backupcopy=yes

set termguicolors
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

filetype plugin on

nnoremap ; :
nnoremap ' ;
nnoremap <silent> <C-_> :split<CR>
nnoremap <silent> <C-\> :vertical split<CR>
nnoremap <silent> <C-h> :vertical resize -5<CR>
nnoremap <silent> <C-j> :resize -3<CR>
nnoremap <silent> <C-k> :resize +3<CR>
nnoremap <silent> <C-l> :vertical resize +5<CR>

nnoremap <silent> <tab><tab> :b#<CR>
nnoremap <silent> <tab>w <C-w><C-w>
nnoremap <silent> <tab>h <C-w><C-h>
nnoremap <silent> <tab>j <C-w><C-j>
nnoremap <silent> <tab>k <C-w><C-k>
nnoremap <silent> <tab>l <C-w><C-l>

" Persistent history
" from simnalamburt/.dotfiles
if has('persistent_undo')
  let vimdir='$HOME/.vim'
  let &runtimepath.=','.vimdir
  let vimundodir=expand(vimdir.'/undodir')
  call system('mkdir -p '.vimundodir)

  let &undodir=vimundodir
  set undofile
endif

" Terminal title
set title
let &titlestring = '[' . $USER . '@' . hostname() . '] %f%( %m%)'

" Terminals
if has('nvim')
  tnoremap <C-j><C-k> <C-\><C-n>
  augroup terminals
    autocmd!
    " No line number for terminal buffers
    autocmd TermOpen * setlocal nonumber
    " Disable whitespace highlighting
    autocmd TermOpen * DisableWhitespace
    " Automatically enter terminal mode
    autocmd TermOpen *sh,*cmd.exe startinsert
    " Close terminal buffer if exit code is 0
    autocmd TermClose *sh,*cmd.exe if !v:event.status | exe 'bdelete! '..expand('<abuf>') | endif
  augroup end
endif

colo tirr
